Import step
MortenTobiasNielsen/Factorio-TAS-Generator pull request #211
Opened 2023-03-19 12:22 UTC by theis999

### #208 Import Step

Added a panel to import steps
It has 2 methods of importing steps, into a template or directly into the steps grid.

#### Import into Steps
This uses a number spinner to place the imported steps an off-set either from the start or the end of the list.
It is not possible to import steps if the spinner is out of range

#### Import into Template 
This creates a new template and populates it with the imported steps.
It names the template based on a text input that needs to be valid before steps can be imported.

#### Validation
The template name and steps offset both have a validation. That will color them red if they are invalid.
There is also a cursory validation on the main import text field. That will disable the buttons, without coloring them.

### Other changes
I've imported wxWidgets.natvis file that should help with debugging. We can remove it if causes issues.
I've changed some of the file filters for better organization.

2023-03-20 19:26 UTC, MortenTobiasNielsen requested changes
This is very well thought out from a user perspective and the code seems pretty good as well - impressive. 👍  

I haven't tried to break it, but it seems to work as intended and the validation seems pretty good. I think most users will use it as intended - copy/paste and insert. So hopefully users won't find some crazy edge case which will break something. :)

2023-03-20 19:26 UTC, MortenTobiasNielsen commented on src/ImportStepsPanel.cpp
> +	}
It seems like this part could be given its own method, so there isn't duplicates of the code in line 161 to 177..

2023-03-20 19:26 UTC, MortenTobiasNielsen commented on src/ImportStepsPanel.cpp
> +bool cMain::validateTemplateName()
Can you walk me though what this is doing. I haven't worked with the GetValidator and TransferFromWindow, and where does import_steps_into_template_ctrl_validator comes from - well GUI_base.h, but you know how did it get there and what does it do? :)

2023-03-20 20:36 UTC, theis999 commented
I am glad you like it. The validation of user input should be solid. Except the imported steps, which follows the logic of open tas. As such it is lenient or broken in the same way.

So you don't need to search for edge cases, since we already know some of them. For instance it is possible to specify invalid recipes for buildings, and other things that are specific to the building type.

2023-03-31 14:21 UTC, MortenTobiasNielsen approved these changes

2023-03-31 14:22 UTC, merged