Refactor utils
MortenTobiasNielsen/Factorio-TAS-Generator pull request #217
Opened 2023-03-20 11:15 UTC by theis999

Moved orientation, priority and inventory to their own files
Moved a bunch of constants only related to opening the tas save file, to their own file

Based on #211 -> #216

2023-03-31 15:18 UTC, MortenTobiasNielsen requested changes

2023-03-31 15:18 UTC, MortenTobiasNielsen commented on src/ImportStepsPanel.cpp
> +		step.Comment = segments.size() == tas_file::step_segment_size || segments.size() == tas_file::step_segment_size_without_colour ? segments[9] : "";
Why not use "Using namespace tas_file" here?

2023-03-31 15:18 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	if (result->goal == tas_file::goal_steelaxe_text)
Why not use "Using namespace tas_file" here?

2023-03-31 15:18 UTC, MortenTobiasNielsen commented on src/utils.h
>  #include "Inventory.h"
I wouldn't guess that utils need these includes - is it just cause it is easier than to figure out where the segments (Priority.h, etc.) is needed? :)

2023-03-31 16:13 UTC, theis999 commented on src/ImportStepsPanel.cpp
> +		step.Comment = segments.size() == tas_file::step_segment_size || segments.size() == tas_file::step_segment_size_without_colour ? segments[9] : "";
It is a good question, and there is some thought to it. I choose to specify that this is from the tas_file *stuff* since this file is otherwise unrelated to working with the tas file.

So since OpenTas and SaveTas are both obviously integrated with the tas file, they will use Using to shorten the constant names, while ImportStepsPanel in my opinion can specify that when needed.

2023-03-31 16:13 UTC, theis999 commented on src/cMain.cpp
> +	if (result->goal == tas_file::goal_steelaxe_text)
I choose to specify that this is from the tas_file *stuff* since this file is otherwise unrelated to working with the tas file.

2023-03-31 16:19 UTC, theis999 commented on src/utils.h
>  #include "Inventory.h"
I chose when i made it, that utils.h would be the header for all utility files. Basicly a collection of utilities. This could be a bad decision, but it made sense when i made it :-)

2023-04-01 13:19 UTC, MortenTobiasNielsen commented
Changes transferred to #228 due to some strange errors.

2023-04-01 13:19 UTC, closed without merging